services:
  receiver:
    container_name: receiver
    image: ghcr.io/ktr03rtk/go-gps-logger/receiver:<IMAGE_TAG>
    volumes:
      - /var/data/raw:/var/data/raw
    network_mode: host
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    environment:
      DIST_DIRECTORY: /var/data/raw/gps
      INTERVAL_SECONDS: 10
    restart: always

  uploader:
    container_name: uploader
    image: ghcr.io/ktr03rtk/go-gps-logger/uploader:<IMAGE_TAG>
    volumes:
      - /var/data/raw:/var/data/raw
      - /var/opt/gps_uploader/cert:/var/opt/gps_uploader/cert
    network_mode: host
    environment:
      SOURCE_DIRECTORY: /var/data/raw/gps
      UPLOAD_INTERVAL_SECONDS: 300
      QOS: 1
      KEEP_ALIVE: 60
      CONNECT_RETRY_DELAY: 10000
      CA_PATH: /var/opt/gps_uploader/cert/ca.crt
      CERT_PATH: /var/opt/gps_uploader/cert/client.crt
      KEY_PATH: /var/opt/gps_uploader/cert/client.key
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_CLIENT: ${MQTT_CLIENT}
      TOPIC: ${TOPIC}
    restart: always

  liveness_client:
    container_name: liveness_client
    image: alpine:latest
    environment:
      API_KEY: ${API_KEY}
      ENDPOINT: ${ENDPOINT}
    restart: always
    entrypoint: ["sh", "-c", "while true ; do wget -qO - --header=\"x-api-key: ${API_KEY}\" ${ENDPOINT} ; sleep 60 ; done ;"]
