services:
  receiver:
    container_name: receiver
    image: ghcr.io/ktr03rtk/go-gps-logger/receiver:<IMAGE_TAG>
    volumes:
      - /var/data/gps:/var/data/gps
    network_mode: host
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    environment:
      DIST_DIRECTORY: /var/data/gps/raw
      INTERVAL_SECONDS: 10
    restart: always
    pull_policy: always

  uploader:
    container_name: uploader
    image: ghcr.io/ktr03rtk/go-gps-logger/uploader:<IMAGE_TAG>
    volumes:
      - /var/data/gps:/var/data/gps
      - /var/opt/gps/cert:/opt/gps_uploader/cert
    network_mode: host
    environment:
      SOURCE_DIRECTORY: /var/data/gps/raw
      UPLOAD_INTERVAL_SECONDS: 300
      QOS: 1
      KEEP_ALIVE: 60
      CONNECT_RETRY_DELAY: 10000
      CA_PATH: /opt/gps_uploader/cert/ca.crt
      CERT_PATH: /opt/gps_uploader/cert/client.crt
      KEY_PATH: /opt/gps_uploader/cert/client.key
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_CLIENT: ${MQTT_CLIENT}
      TOPIC: ${TOPIC}
