services:
  uploader:
    container_name: uploader
    build:
      context: .
      target: build-stage
      args:
        TZ: Asia/Tokyo
    network_mode: host
    tty: true
    volumes:
      - /var/data/gps:/var/data/gps
      - ${PWD}/:/opt/gps_uploader
      - ${PWD}/crt/ca.crt:${CA_PATH}
      - ${PWD}/crt/client.crt:${CERT_PATH}
      - ${PWD}/crt/client.key:${KEY_PATH}
    environment:
      SOURCE_DIRECTORY: /var/data/gps/raw
      UPLOADE_INTERVAL_SECONDS: 60
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_CLIENT: ${MQTT_CLIENT}
      TOPIC: ${TOPIC}
      QOS: ${QOS}
      KEEP_ALIVE: ${KEEP_ALIVE}
      CONNECT_RETRY_DELAY: ${CONNECT_RETRY_DELAY}
      DELAY_BETWEEN_MESSAGES: ${DELAY_BETWEEN_MESSAGES}
      CA_PATH: ${CA_PATH}
      CERT_PATH: ${CERT_PATH}
      KEY_PATH: ${KEY_PATH}
