name: Create and publish a Docker image

on:
  push
  # push:
  #   branches:
  #     - "main"

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml
    with:
      targetDir: receiver

  build-and-push-image:
    needs: test
    uses: ./.github/workflows/build-workflow.yml
    with:
      targetDir: receiver

  trivy:
    runs-on: ubuntu-20.04
    needs: build-and-push-image
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-and-push-image.outputs.image-ref }}
          format: table
          exit-code: 1
          severity: CRITICAL
